#!/bin/sh /etc/rc.common

START=99
SERVICE=alpine-fan-control

PROG="alpine-fan-controller"
USE_PROCD=1
ENABLED=0

run_alpine_fan_control()
{
	local enable
	config_get_bool enable $1 enable
	if [ "$enable" != "1" ]; then
		logger "alpine-fan-control is disabled. check configuration?"
		return
	fi
	ENABLED=1
}

start_service()
{
	ENABLED=0
	config_load alpine-fan-control
	config_foreach run_alpine_fan_control alpine-fan-control
	if [ "$ENABLED" != "1" ]; then
		#logger "alpine-fan-control config is empty."
		return 0
	fi
	logger -t "$PROG" "start..."

	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}

stop_service()
{
	procd_kill "$PROG"
}

reload_service()
{
	stop
	start
}

service_triggers()
{
	procd_add_reload_trigger "/etc/config/alpine-fan-control" "alpine-fan-control"
}
